### PR TITLE
Support for HTML header comments in subgallery's readme.md

### LINKED ISSUE #85: Issue with header in README.md
When a `README.md` has a header (like a licence header) as a html comment, like so with one of mkdocs gallery's projects examples `docs/examples/no_output/README.md`:
```markdown
<!--
  Header here.
-->
## No image output examples

This section gathers examples which don't produce any figures. Some examples
only output to standard output, others demonstrate how Mkdocs-Gallery handles
examples with errors.
```

The rendering is broken:
Screenshot from 2023-11-22 12-20-38

### PR DESCRIPTION
**Pull request by AntoineD**
Fixes #85

### CODE REVIEW

**Comment by smarie** [comment]
Thanks @AntoineD . Can you please add a changelog.md entry for your PR ?

```
### 0.7.11 - (in progress)

 - (here)
```

(please look at the previous changelog entries as examples)

**Comment by AntoineD** [comment]
> Thanks @AntoineD . Can you please add a changelog.md entry for your PR ?
> 
> ```
> ### 0.7.11 - (in progress)
> 
>  - (here)
> ```
> 
> (please look at the previous changelog entries as examples)

Done.

**Comment by smarie** [comment]
I am not able to see this change @AntoineD , did you push the commit ?

**Comment by AntoineD** [comment]
> I am not able to see this change @AntoineD , did you push the commit ?

My bad, sorry about that, that should be OK now.

**Comment by smarie** [comment]
Thanks @AntoineD  !

**Pull request merged**
