### PR TITLE
Add a scraper for `pyvista`

### PR DESCRIPTION
**Pull request by Louis-Pujol**
Hello, in this PR I propose an implementation of a scraper for the [pyvista](https://docs.pyvista.org/version/stable/) library.

The scraper is a slight modification of the [pyvista's sphinx-gallery scraper](https://github.com/pyvista/pyvista/blob/main/pyvista/plotting/utilities/sphinx_gallery.py). I integrated it following the `mayavi` scraper already implemented.

It allows to show static or animated 3d scenes created with `pyvista`. I added an example to the examples gallery. I moved the definition of `image_scrapers` from `mkdocs.yml` to `gallery_conf.py`. I found this clearer as pyvista is configured in `gallery_conf.py`.

I also added pyvista as a dependency in `MKDOCS_GALLERY_EXAMPLES_REQS` in `noxfile.py`.

### CODE REVIEW

**Comment by Louis-Pujol** [comment]
Hi ! Just realized reading [PR#59](https://github.com/smarie/mkdocs-gallery/pull/69),that @GenevieveBuckley  and I want at the same time adding `plot_10_...` to the examples gallery. @smarie do you want me to rename my example `plot_11_pyvista.py` ?

**Comment by smarie** [comment]
Hi @Louis-Pujol , yes please use the "11" number

**Comment by Louis-Pujol** [comment]
@smarie sure, I'll wait for it.

**Comment by smarie** [comment]
Hi @Louis-Pujol , would you like to update your PR now that #69 has been merged ?
Thanks !

**Pull request closed without merging**
